services:
    sylius.google_tag_manager.enhanced_ecommerce_tracking.tag_manager.add_transaction:
        class: GtmEnhancedEcommercePlugin\TagManager\AddTransaction
        arguments:
            - "@google_tag_manager"
            - "@sylius.context.channel"
            - "@sylius.context.currency"
