services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    sylius.google_tag_manager.enhanced_ecommerce_tracking.tag_manager.add_transaction:
        class: SyliusGtmEnhancedEcommercePlugin\TagManager\AddTransaction
        arguments:
            - "@google_tag_manager"
            - "@sylius.context.channel"
            - "@sylius.context.currency"

    sylius.google_tag_manager.enhanced_ecommerce_tracking.tag_manager.checkout_step:
        class: SyliusGtmEnhancedEcommercePlugin\TagManager\CheckoutStep
        arguments:
            - "@google_tag_manager"

    sylius.google_tag_manager.enhanced_ecommerce.tracking.resolver.product_detail_impression_data:
        class: SyliusGtmEnhancedEcommercePlugin\Resolver\ProductDetailImpressionDataResolver
        arguments:
            - "@sylius.calculator.product_variant_price"
            - "@sylius.context.channel"
            - "@sylius.google_tag_manager.enhanced_ecommerce_tracking.object.factory.product_detail_impression"
            - "@sylius.google_tag_manager.enhanced_ecommerce_tracking.object.factory.product_detail"

    sylius.google_tag_manager.enhanced_ecommerce_tracking.resolver.checkout_step:
        class: SyliusGtmEnhancedEcommercePlugin\Resolver\CheckoutStepResolver

    sylius.google_tag_manager.enhanced_ecommerce_tracking.tag_manager.currency_code:
        class: SyliusGtmEnhancedEcommercePlugin\TagManager\CurrencyCode
        arguments:
            - "@google_tag_manager"
            - "@sylius.context.currency"

    sylius.google_tag_manager.enhanced_ecommerce_tracking.global.listener.sylius.shop.layout.head:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - 'SyliusGtmEnhancedEcommercePlugin::Global/head.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.head, method: onBlockEvent }

    sylius.google_tag_manager.enhanced_ecommerce_tracking.object.factory.product_detail:
        class: SyliusGtmEnhancedEcommercePlugin\Object\Factory\ProductDetailFactory

    sylius.google_tag_manager.enhanced_ecommerce_tracking.object.factory.product_detail_impression:
        class: SyliusGtmEnhancedEcommercePlugin\Object\Factory\ProductDetailImpressionFactory
