services:
    sylius.google_tag_manager.enhanced_ecommerce_tracking.listener.sylius.shop.layout.head:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@GtmEnhancedEcommercePlugin/ProductImpressions/head.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.head, method: onBlockEvent }

    sylius.google_tag_manager.enhanced_ecommerce_tracking.listener.sylius.shop.layout.after_body:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@GtmEnhancedEcommercePlugin/ProductImpressions/foot.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.after_body, method: onBlockEvent }

    sylius.google_tag_manager.enhanced_ecommerce_tracking.listener.sylius.shop.product.index.before_list:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@GtmEnhancedEcommercePlugin/ProductImpressions/products.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.product.index.before_list, method: onBlockEvent }
